version: '3'
volumes:
  postgresql-data:
    driver: 'local'
services:
  postgresql:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - default
